name: alarm
description: alarm app nfc
publish_to: none

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: 19.4.2
  flutter_timezone: ^4.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image: ^4.5.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shadcn_ui: 0.37.4
  flutter_launcher_icons:
  timezone: ^0.10.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: ^3.16.9

flutter:
  uses-material-design: true
  assets:
    - icons/
    - sound/

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"


flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  image_path: "icons/box.png"